### ISSUE TITLE
Maintenance: Automate releases and publishing library as an npm package

### ISSUE THREAD

**Issue by shdq** [shdq/spartak-ui#14]
Create a GitHub action workflows to achieve the following steps:

- [x] Build the project #1 
- [x] Create release with GitHub Actions #56 
- [x] Publish build to `npm` registry #59 

The build step is ready, `npm build` creates a bundle using `rollup` with the only dependency `stitches` (`css-in-js` library) and corresponding types. The build was tested as a local package with `npm pack` and installed as a dependency from the file.

Workflows for automation of release creation and publishing to `npm` are implemented using GitHub Actions.

This issue is intended to track all the steps to the release and publishing process.

- [x] I updated library imports in examples.
