### ISSUE TITLE
Feature request: Dark theme support

### ISSUE THREAD

**Issue by shdq** [shdq/spartak-ui#7]
**Description of the feature**

Dark theme support for the components.

**Tasks:**

- [x] Decide on the API and implementation of this feature
- [x] Adjust the default theme tokens to satisfy a18y requirements for coloring background/foreground
- [x] Introduce `ThemeProvider` and `useTheme` hooks to use themes in apps
- [x] Add/update docs on how to use it and add a dark theme to the user's app
